name: 🔢 Hash Error
description: Open an issue about a package's hash is incorrect.
title: "xxx@x.x.x: hash check failed"
labels:
    [
        "bug",
    ]
body:
    - type: markdown
      attributes:
          value:
              |
              ### ⚠️ Title Format Requirements
              **Please strictly follow the format below**, otherwise the automation will fail:
              require: `PackageName@Version: hash check failed`
              Example: `PSCompletions@5.4.0: hash check failed`
    - type: checkboxes
      attributes:
          label: Prerequisites
          options:
              - label:
                    |
                    I have used the predefined issue title.
                    e.g. PSCompletions@5.4.0: hash check failed
                required: true
              - label: I have verified that I am using the latest version of Scoop and corresponding bucket.
                required: true
    - type: input
      attributes:
          label: Package Name and Version
          description:
              |
              Name and version of package (install name) which has incorrect hash.
              e.g. PSCompletions@5.4.0
          placeholder: PSCompletions@5.4.0
      validations:
          required: true
