name: 🔢 Hash 错误
description: 提交一个包含 hash 错误的包的 issue。
title: "xxx@x.x.x: hash check failed"
labels:
    [
        "bug",
    ]
body:
    - type: markdown
      attributes:
          value:
              |
              ### ⚠️ 标题格式要求
              **请严格按以下格式填写标题**，否则自动化工具无法处理 hash 错误：
              格式: `包名@版本号: hash check failed`
              示例：`PSCompletions@5.5.0: hash check failed`
    - type: checkboxes
      attributes:
          label: 前提条件
          options:
              - label:
                    |
                    我确定使用了正确的 Issue 标题格式。
                    例如: PSCompletions@5.5.0: hash check failed
                required: true
              - label: 我确定正在使用最新版本的 Scoop 和相应的存储桶。
                required: true
