name: Commented Pull Request

on:
  issue_comment:
    types: [created]

jobs:
  # PR 中评论 /verify 自动校验 PR 中提交的 manifest 文件是否符合规范
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: PullRequestHandler
        uses: ScoopInstaller/GithubActions@main
        if: startsWith(github.event.comment.body, '/verify')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
